version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ms-contabilidad-db
    environment:
      POSTGRES_DB: contabilidad_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - contabilidad-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-contabilidad:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-contabilidad-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/contabilidad_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - contabilidad-network

volumes:
  postgres_data:


networks:
  contabilidad-network:
    driver: bridge
